apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: p-6650-6650-tcp
      port: 6650
      protocol: TCP
      targetPort: 6650
    - name: p-8080-8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: p-8090-8080-tcp
      port: 8090
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}