apiVersion: v1
kind: ConfigMap
metadata:
  name: config-{{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
data:
  local.json: {{ toYaml .Values.local_json | indent 4 }}