{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
{{- if .Values.sealedsecret.debezium.config.database.dicco.password }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-debezium-dicco-cred

spec:
  encryptedData:
    password:  {{ .Values.sealedsecret.debezium.config.database.dicco.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-debezium-dicco-cred
{{- end }}