apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
    appType: {{ .Values.appType }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: scrape
      targetPort: {{ .Values.service.port }}
      protocol: TCP
    - port: {{ .Values.service.rsocket_port }}
      name: rsocket
      targetPort: {{ .Values.service.rsocket_port }}
      protocol: TCP

  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}